"""Remove last_accessed_at column from jwt_sessions table

Revision ID: 3d5e460a733e
Revises: 2a24dc1bc456
Create Date: 2024-08-21 14:03:00.067656

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '3d5e460a733e'
down_revision: Union[str, None] = '2a24dc1bc456'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jwt_sessions', 'last_accessed_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jwt_sessions', sa.Column('last_accessed_at', mysql.DATETIME(), nullable=True))
    # ### end Alembic commands ###
