"""add notifications table

Revision ID: aab5746a66ea
Revises: dc7ba21b1356
Create Date: 2024-09-13 14:35:33.761354

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'aab5746a66ea'
down_revision: Union[str, None] = 'dc7ba21b1356'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('friend_requests', 'status',
               existing_type=mysql.ENUM('pending', 'accepted', 'declined', 'cancelled'),
               type_=sa.Enum('pending', 'accepted', 'rejected', 'cancelled', name='friendrequeststatus'),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('friend_requests', 'status',
               existing_type=sa.Enum('pending', 'accepted', 'rejected', 'cancelled', name='friendrequeststatus'),
               type_=mysql.ENUM('pending', 'accepted', 'declined', 'cancelled'),
               existing_nullable=False)
    # ### end Alembic commands ###
