"""Add blocked users, notifications, and privacy settings

Revision ID: dc7ba21b1356
Revises: e5ce8e7169d9
Create Date: 2024-09-10 21:32:57.175752

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dc7ba21b1356'
down_revision: Union[str, None] = 'e5ce8e7169d9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blocked_users',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('blocked_user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['blocked_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'blocked_user_id')
    )
    op.add_column('users', sa.Column('privacy_friends_list', sa.Enum('public', 'friends', 'private', name='privacy_enum'), nullable=False))
    op.add_column('users', sa.Column('privacy_friend_requests', sa.Enum('everyone', 'friends_of_friends', 'none', name='privacy_requests_enum'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'privacy_friend_requests')
    op.drop_column('users', 'privacy_friends_list')
    op.drop_table('blocked_users')
    # ### end Alembic commands ###
